include ~/.cache/wal/colors-kitty.conf

# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMono Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

# Cursor
cursor_trail 3
cursor_shape beam

# Fix bg
resize_in_steps no
resize_debounce_time 0 0

# Background
# background_opacity 0.5
# background_blur 1

# No close confirmation
confirm_os_window_close 0

map ctrl+/ layout_action mirror toggle
map ctrl+shift+, load_config_file


