[config]

[templates.yazi]
input_path = './templates/yazi.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.niri]
input_path = './templates/niri.kdl'
output_path = '~/.config/niri/config.kdl'
