exec-once = systemctl --user start hyprpolkitagent
exec-once = hypridle
exec-once = hyprsunset

# Clipboard
exec-once = wl-paste --type text --watch cliphist store # Stores text data
exec-once = wl-paste --type image --watch cliphist store # Stores image data

exec-once = swww-daemon
exec-once = waybar

exec-once = $discord

exec-once = hyprpm reload
