# Ignore maximize requests from apps. You'll probably like this.
windowrulev2 = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Disable shadow for tiled windows
windowrulev2 = noshadow,floating:0

## Tags
windowrulev2 = tag +browser, class:^(brave)(.*)$
windowrulev2 = tag +browser, class:^(firefox)(.*)$
windowrulev2 = tag +browser, class:^(.*)(chrome)(.*)$
windowrulev2 = tag +browser, class:^(chromium)(.*)$

windowrulev2 = tag +code, class:^([Cc]ode)(.*)$
windowrulev2 = tag +code, class:^([Cc]odium)(.*)$
windowrulev2 = tag +code, class:^(neovim)$

windowrulev2 = tag +music, class:^([Ss]potify)$

windowrulev2 = tag +chat, class:^([Dd]iscord)(.*)$
windowrulev2 = tag +chat, class:^([Vv]esktop)(.*)$

# Move window to workspace
windowrulev2 = workspace 1, tag:browser
windowrulev2 = workspace 4, tag:code
windowrulev2 = workspace 5 silent, tag:music
windowrulev2 = workspace 6 silent, tag:chat

# fuzzel
layerrule = blur, fuzzel
layerrule = ignorealpha, fuzzel

# waybar
layerrule = blur, waybar
layerrule = ignorealpha, waybar
layerrule = animation slidevert, waybar

# swww
layerrule = animation fade, swww-daemon

# hyprshot/hyprpicker
layerrule = noanim, hyprpicker
layerrule = noanim, selection
