# Ignore maximize requests from apps. You'll probably like this.
windowrulev2 = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrulev2 = nofocus, class:^$, title:^$, xwayland:1, floating:1, fullscreen:0, pinned:0

## Tags
windowrulev2 = tag +browser, class:^(brave)(.*)$
windowrulev2 = tag +browser, class:^(firefox)(.*)$
windowrulev2 = tag +browser, class:^(.*)(chrome)(.*)$
windowrulev2 = tag +browser, class:^(chromium)(.*)$

windowrulev2 = tag +code, class:^([Cc]ode)(.*)$
windowrulev2 = tag +code, class:^([Cc]odium)(.*)$
windowrulev2 = tag +code, class:^(neovim)$
windowrulev2 = tag +code, class:^(kitty)$, title:^(nvim)(.*)$

windowrulev2 = tag +music, class:^([Ss]potify)$

windowrulev2 = tag +chat, class:^([Dd]iscord)(.*)$
windowrulev2 = tag +chat, class:^([Vv]esktop)(.*)$

windowrulev2 = tag +sys, class:^(pavucontrol)(.*)$
windowrulev2 = tag +sys, class:^(taskmgr)(.*)$
windowrulev2 = tag +sys, class:^(bluetoothmgr)(.*)$
windowrulev2 = tag +sys, class:^(wall-selector)(.*)$
windowrulev2 = tag +sys, class:^(io.missioncenter.MissionCenter)(.*)$

# Floating windows
windowrulev2 = float, tag:sys

windowrulev2 = size 862  574, class:^(pavucontrol)(.*)$
windowrulev2 = size 862  574, class:^(taskmgr)(.*)$
windowrulev2 = size 862  574, class:^(bluetoothmgr)(.*)$
windowrulev2 = size 1272 582, class:^(wall-selector)(.*)$
windowrulev2 = size 1272 582, class:^(io.missioncenter.MissionCenter)(.*)$

# Move window to workspace
windowrulev2 = workspace 1, tag:browser
windowrulev2 = workspace 4, tag:code
windowrulev2 = workspace 5 silent, tag:music
windowrulev2 = workspace 6 silent, tag:chat

# Center floating windows
windowrulev2 = center, floating:1

# Disable shadow for tiled windows
windowrulev2 = noshadow, floating:0

# fuzzel
layerrule = blur, fuzzel
layerrule = ignorealpha, fuzzel
layerrule = animation slide bottom, fuzzel

# Mako
layerrule = blur, notifications
layerrule = ignorealpha, notifications
layerrule = animation slide right, notifications

# waybar
layerrule = blur, waybar
layerrule = ignorealpha, waybar
layerrule = animation slide top, waybar

# wlogout
layerrule = blur, logout_dialog
layerrule = ignorealpha, logout_dialog
layerrule = animation fade, logout_dialog

# swww
layerrule = animation fade, swww-daemon

# hyprshot/hyprpicker
layerrule = noanim, hyprpicker
layerrule = noanim, selection
