
$background = rgba(141315ff)
$background_hex = 141315

$error = rgba(ffb4abff)
$error_hex = ffb4ab

$error_container = rgba(93000aff)
$error_container_hex = 93000a

$inverse_on_surface = rgba(313032ff)
$inverse_on_surface_hex = 313032

$inverse_primary = rgba(5d5b7cff)
$inverse_primary_hex = 5d5b7c

$inverse_surface = rgba(e5e1e4ff)
$inverse_surface_hex = e5e1e4

$on_background = rgba(e5e1e4ff)
$on_background_hex = e5e1e4

$on_error = rgba(690005ff)
$on_error_hex = 690005

$on_error_container = rgba(ffdad6ff)
$on_error_container_hex = ffdad6

$on_primary = rgba(2f2d4cff)
$on_primary_hex = 2f2d4c

$on_primary_container = rgba(e0dcffff)
$on_primary_container_hex = e0dcff

$on_primary_fixed = rgba(1a1835ff)
$on_primary_fixed_hex = 1a1835

$on_primary_fixed_variant = rgba(454363ff)
$on_primary_fixed_variant_hex = 454363

$on_secondary = rgba(302f3cff)
$on_secondary_hex = 302f3c

$on_secondary_container = rgba(e2deefff)
$on_secondary_container_hex = e2deef

$on_secondary_fixed = rgba(1b1a27ff)
$on_secondary_fixed_hex = 1b1a27

$on_secondary_fixed_variant = rgba(474553ff)
$on_secondary_fixed_variant_hex = 474553

$on_surface = rgba(e5e1e4ff)
$on_surface_hex = e5e1e4

$on_surface_variant = rgba(c8c5ceff)
$on_surface_variant_hex = c8c5ce

$on_tertiary = rgba(452639ff)
$on_tertiary_hex = 452639

$on_tertiary_container = rgba(ffd4eaff)
$on_tertiary_container_hex = ffd4ea

$on_tertiary_fixed = rgba(2e1224ff)
$on_tertiary_fixed_hex = 2e1224

$on_tertiary_fixed_variant = rgba(5e3c50ff)
$on_tertiary_fixed_variant_hex = 5e3c50

$outline = rgba(928f98ff)
$outline_hex = 928f98

$outline_variant = rgba(47464dff)
$outline_variant_hex = 47464d

$primary = rgba(c6c2e9ff)
$primary_hex = c6c2e9

$primary_container = rgba(454363ff)
$primary_container_hex = 454363

$primary_fixed = rgba(e3dfffff)
$primary_fixed_hex = e3dfff

$primary_fixed_dim = rgba(c6c2e9ff)
$primary_fixed_dim_hex = c6c2e9

$scrim = rgba(000000ff)
$scrim_hex = 000000

$secondary = rgba(c8c4d5ff)
$secondary_hex = c8c4d5

$secondary_container = rgba(474553ff)
$secondary_container_hex = 474553

$secondary_fixed = rgba(e4e0f2ff)
$secondary_fixed_hex = e4e0f2

$secondary_fixed_dim = rgba(c8c4d5ff)
$secondary_fixed_dim_hex = c8c4d5

$shadow = rgba(000000ff)
$shadow_hex = 000000

$source_color = rgba(454363ff)
$source_color_hex = 454363

$surface = rgba(141315ff)
$surface_hex = 141315

$surface_bright = rgba(3a393bff)
$surface_bright_hex = 3a393b

$surface_container = rgba(201f22ff)
$surface_container_hex = 201f22

$surface_container_high = rgba(2a292cff)
$surface_container_high_hex = 2a292c

$surface_container_highest = rgba(353437ff)
$surface_container_highest_hex = 353437

$surface_container_low = rgba(1c1b1eff)
$surface_container_low_hex = 1c1b1e

$surface_container_lowest = rgba(0e0e10ff)
$surface_container_lowest_hex = 0e0e10

$surface_dim = rgba(141315ff)
$surface_dim_hex = 141315

$surface_tint = rgba(c6c2e9ff)
$surface_tint_hex = c6c2e9

$surface_variant = rgba(47464dff)
$surface_variant_hex = 47464d

$tertiary = rgba(e8bad2ff)
$tertiary_hex = e8bad2

$tertiary_container = rgba(5e3c50ff)
$tertiary_container_hex = 5e3c50

$tertiary_fixed = rgba(ffd8ebff)
$tertiary_fixed_hex = ffd8eb

$tertiary_fixed_dim = rgba(e8bad2ff)
$tertiary_fixed_dim_hex = e8bad2

