
$background = rgba(131314ff)
$background_hex = 131314

$error = rgba(ffb4abff)
$error_hex = ffb4ab

$error_container = rgba(93000aff)
$error_container_hex = 93000a

$inverse_on_surface = rgba(313031ff)
$inverse_on_surface_hex = 313031

$inverse_primary = rgba(5c5d6fff)
$inverse_primary_hex = 5c5d6f

$inverse_surface = rgba(e5e1e3ff)
$inverse_surface_hex = e5e1e3

$on_background = rgba(e5e1e3ff)
$on_background_hex = e5e1e3

$on_error = rgba(690005ff)
$on_error_hex = 690005

$on_error_container = rgba(ffdad6ff)
$on_error_container_hex = ffdad6

$on_primary = rgba(2e2f3fff)
$on_primary_hex = 2e2f3f

$on_primary_container = rgba(ffffffff)
$on_primary_container_hex = ffffff

$on_primary_fixed = rgba(191a29ff)
$on_primary_fixed_hex = 191a29

$on_primary_fixed_variant = rgba(444656ff)
$on_primary_fixed_variant_hex = 444656

$on_secondary = rgba(303037ff)
$on_secondary_hex = 303037

$on_secondary_container = rgba(e1dfe8ff)
$on_secondary_container_hex = e1dfe8

$on_secondary_fixed = rgba(1b1b22ff)
$on_secondary_fixed_hex = 1b1b22

$on_secondary_fixed_variant = rgba(46464eff)
$on_secondary_fixed_variant_hex = 46464e

$on_surface = rgba(e5e1e3ff)
$on_surface_hex = e5e1e3

$on_surface_variant = rgba(c8c5cdff)
$on_surface_variant_hex = c8c5cd

$on_tertiary = rgba(3d2b36ff)
$on_tertiary_hex = 3d2b36

$on_tertiary_container = rgba(ffffffff)
$on_tertiary_container_hex = ffffff

$on_tertiary_fixed = rgba(271621ff)
$on_tertiary_fixed_hex = 271621

$on_tertiary_fixed_variant = rgba(55414dff)
$on_tertiary_fixed_variant_hex = 55414d

$outline = rgba(919096ff)
$outline_hex = 919096

$outline_variant = rgba(47464cff)
$outline_variant_hex = 47464c

$primary = rgba(c5c5d9ff)
$primary_hex = c5c5d9

$primary_container = rgba(626375ff)
$primary_container_hex = 626375

$primary_fixed = rgba(e1e1f6ff)
$primary_fixed_hex = e1e1f6

$primary_fixed_dim = rgba(c5c5d9ff)
$primary_fixed_dim_hex = c5c5d9

$scrim = rgba(000000ff)
$scrim_hex = 000000

$secondary = rgba(c7c5ceff)
$secondary_hex = c7c5ce

$secondary_container = rgba(46464eff)
$secondary_container_hex = 46464e

$secondary_fixed = rgba(e3e1ebff)
$secondary_fixed_hex = e3e1eb

$secondary_fixed_dim = rgba(c7c5ceff)
$secondary_fixed_dim_hex = c7c5ce

$shadow = rgba(000000ff)
$shadow_hex = 000000

$source_color = rgba(626375ff)
$source_color_hex = 626375

$surface = rgba(131314ff)
$surface_hex = 131314

$surface_bright = rgba(3a393aff)
$surface_bright_hex = 3a393a

$surface_container = rgba(201f21ff)
$surface_container_hex = 201f21

$surface_container_high = rgba(2a2a2bff)
$surface_container_high_hex = 2a2a2b

$surface_container_highest = rgba(353436ff)
$surface_container_highest_hex = 353436

$surface_container_low = rgba(1c1b1dff)
$surface_container_low_hex = 1c1b1d

$surface_container_lowest = rgba(0e0e0fff)
$surface_container_lowest_hex = 0e0e0f

$surface_dim = rgba(131314ff)
$surface_dim_hex = 131314

$surface_tint = rgba(c5c5d9ff)
$surface_tint_hex = c5c5d9

$surface_variant = rgba(47464cff)
$surface_variant_hex = 47464c

$tertiary = rgba(dabfceff)
$tertiary_hex = dabfce

$tertiary_container = rgba(745e6bff)
$tertiary_container_hex = 745e6b

$tertiary_fixed = rgba(f8dbeaff)
$tertiary_fixed_hex = f8dbea

$tertiary_fixed_dim = rgba(dabfceff)
$tertiary_fixed_dim_hex = dabfce

