
$background = rgba(141315ff)
$background_hex = 141315

$error = rgba(ffb4abff)
$error_hex = ffb4ab

$error_container = rgba(93000aff)
$error_container_hex = 93000a

$inverse_on_surface = rgba(313032ff)
$inverse_on_surface_hex = 313032

$inverse_primary = rgba(645978ff)
$inverse_primary_hex = 645978

$inverse_surface = rgba(e6e1e4ff)
$inverse_surface_hex = e6e1e4

$on_background = rgba(e6e1e4ff)
$on_background_hex = e6e1e4

$on_error = rgba(690005ff)
$on_error_hex = 690005

$on_error_container = rgba(ffdad6ff)
$on_error_container_hex = ffdad6

$on_primary = rgba(352c48ff)
$on_primary_hex = 352c48

$on_primary_container = rgba(beb1d5ff)
$on_primary_container_hex = beb1d5

$on_primary_fixed = rgba(1f1732ff)
$on_primary_fixed_hex = 1f1732

$on_primary_fixed_variant = rgba(4c4260ff)
$on_primary_fixed_variant_hex = 4c4260

$on_secondary = rgba(332e3bff)
$on_secondary_hex = 332e3b

$on_secondary_container = rgba(e9e1f1ff)
$on_secondary_container_hex = e9e1f1

$on_secondary_fixed = rgba(1e1a25ff)
$on_secondary_fixed_hex = 1e1a25

$on_secondary_fixed_variant = rgba(4a4552ff)
$on_secondary_fixed_variant_hex = 4a4552

$on_surface = rgba(e6e1e4ff)
$on_surface_hex = e6e1e4

$on_surface_variant = rgba(cac4cdff)
$on_surface_variant_hex = cac4cd

$on_tertiary = rgba(462735ff)
$on_tertiary_hex = 462735

$on_tertiary_container = rgba(d9aabcff)
$on_tertiary_container_hex = d9aabc

$on_tertiary_fixed = rgba(2e1220ff)
$on_tertiary_fixed_hex = 2e1220

$on_tertiary_fixed_variant = rgba(5f3c4bff)
$on_tertiary_fixed_variant_hex = 5f3c4b

$outline = rgba(948f97ff)
$outline_hex = 948f97

$outline_variant = rgba(49454dff)
$outline_variant_hex = 49454d

$primary = rgba(cec1e5ff)
$primary_hex = cec1e5

$primary_container = rgba(2f2642ff)
$primary_container_hex = 2f2642

$primary_fixed = rgba(eaddffff)
$primary_fixed_hex = eaddff

$primary_fixed_dim = rgba(cec1e5ff)
$primary_fixed_dim_hex = cec1e5

$scrim = rgba(000000ff)
$scrim_hex = 000000

$secondary = rgba(cbc3d3ff)
$secondary_hex = cbc3d3

$secondary_container = rgba(4c4754ff)
$secondary_container_hex = 4c4754

$secondary_fixed = rgba(e8dff0ff)
$secondary_fixed_hex = e8dff0

$secondary_fixed_dim = rgba(cbc3d3ff)
$secondary_fixed_dim_hex = cbc3d3

$shadow = rgba(000000ff)
$shadow_hex = 000000

$source_color = rgba(2f2642ff)
$source_color_hex = 2f2642

$surface = rgba(141315ff)
$surface_hex = 141315

$surface_bright = rgba(3a383bff)
$surface_bright_hex = 3a383b

$surface_container = rgba(201f21ff)
$surface_container_hex = 201f21

$surface_container_high = rgba(2b292cff)
$surface_container_high_hex = 2b292c

$surface_container_highest = rgba(363437ff)
$surface_container_highest_hex = 363437

$surface_container_low = rgba(1c1b1dff)
$surface_container_low_hex = 1c1b1d

$surface_container_lowest = rgba(0f0e10ff)
$surface_container_lowest_hex = 0f0e10

$surface_dim = rgba(141315ff)
$surface_dim_hex = 141315

$surface_tint = rgba(cec1e5ff)
$surface_tint_hex = cec1e5

$surface_variant = rgba(49454dff)
$surface_variant_hex = 49454d

$tertiary = rgba(eabaccff)
$tertiary_hex = eabacc

$tertiary_container = rgba(40212fff)
$tertiary_container_hex = 40212f

$tertiary_fixed = rgba(ffd8e6ff)
$tertiary_fixed_hex = ffd8e6

$tertiary_fixed_dim = rgba(eabaccff)
$tertiary_fixed_dim_hex = eabacc

