# : Manager [[[

[mgr]
cwd = { fg = "#f6dddc" }

# Tab
tab_active = { fg = "#680017", bg = "#ffb3b5", bold = true }
tab_inactive = { fg = "#ffdada", bg = "#40000b" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ff9f5e", bg = "#ff9f5e" }
marker_cut = { fg = "#ffdcc4", bg = "#ffdcc4" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#ffb77f", bg = "#ffb77f" }

# Count
count_copied = { fg = "#2f1500", bg = "#ffdcc4" }
count_cut = { fg = "#2f1500", bg = "#ffdcc4" }
count_selected = { fg = "#680017", bg = "#ffb77f" }

# Border
border_symbol = "│"
border_style  = { fg = "#ffb3b5" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#680017", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#ffb3b5", fg = "#680017", bold = true }
normal_alt  = { bg = "#594141", fg = "#e0bebf" }

# Select mode
select_main = { bg = "#ffb3b5", fg = "#591a20", bold = true }
select_alt  = { bg = "#594141", fg = "#e0bebf" }

# Unset mode
unset_main = { bg = "#ffb77f", fg = "#4e2600", bold = true }
unset_alt  = { bg = "#594141", fg = "#e0bebf" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#ffb3b5", bg = "#453535" }
progress_error = { fg = "#ffb4ab", bg = "#453535" }

# Permissions
permissions_t = { fg = "#ff1a20" }
permissions_w = { fg = "#e56400" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#ff812b" }
permissions_s = { fg = "#ff4141" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#ffb3b5" }
active = { fg = "#ffb77f", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#ffb3b5" }
value = { fg = "#f6dddc" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#ffb3b5", bg = "#680017" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#ffb3b5" }
title = {}
hovered = { fg = "#ffdcc4", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#453535" }
cand = { fg = "#ffb3b5" }
rest = { fg = "#680017" }
desc = { fg = "#f6dddc" }
separator = " ▶ "
separator_style = { fg = "#f6dddc" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#f6dddc" }
run = { fg = "#f6dddc" }
footer = { fg = "#591a20", bg = "#ffb3b5" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#ffb77f" }
title_warn = { fg = "#ffb3b5" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#f6dddc" },
    { name = "*/", fg = "#ffb3b5" },
]

# : ]]]
