# : Manager [[[

[mgr]
cwd = { fg = "#efdfe1" }

# Tab
tab_active = { fg = "#541d32", bg = "#ffb0c9", bold = true }
tab_inactive = { fg = "#ffd9e2", bg = "#3a071d" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ffa15c", bg = "#ffa15c" }
marker_cut = { fg = "#ffdcc2", bg = "#ffdcc2" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#efbd94", bg = "#efbd94" }

# Count
count_copied = { fg = "#2e1500", bg = "#ffdcc2" }
count_cut = { fg = "#2e1500", bg = "#ffdcc2" }
count_selected = { fg = "#541d32", bg = "#efbd94" }

# Border
border_symbol = "│"
border_style  = { fg = "#ffb0c9" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#541d32", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#ffb0c9", fg = "#541d32", bold = true }
normal_alt  = { bg = "#514347", fg = "#d5c2c6" }

# Select mode
select_main = { bg = "#e2bdc7", fg = "#422931", bold = true }
select_alt  = { bg = "#514347", fg = "#d5c2c6" }

# Unset mode
unset_main = { bg = "#efbd94", fg = "#48290c", bold = true }
unset_alt  = { bg = "#514347", fg = "#d5c2c6" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#ffb0c9", bg = "#413739" }
progress_error = { fg = "#ffb4ab", bg = "#413739" }

# Permissions
permissions_t = { fg = "#b3536d" }
permissions_w = { fg = "#cc6c1e" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#ff8429" }
permissions_s = { fg = "#ff406d" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#ffb0c9" }
active = { fg = "#efbd94", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#ffb0c9" }
value = { fg = "#efdfe1" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#ffb0c9", bg = "#541d32" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#ffb0c9" }
title = {}
hovered = { fg = "#ffdcc2", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#413739" }
cand = { fg = "#ffb0c9" }
rest = { fg = "#541d32" }
desc = { fg = "#efdfe1" }
separator = " ▶ "
separator_style = { fg = "#efdfe1" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#efdfe1" }
run = { fg = "#efdfe1" }
footer = { fg = "#422931", bg = "#e2bdc7" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#efbd94" }
title_warn = { fg = "#ffb0c9" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#efdfe1" },
    { name = "*/", fg = "#ffb0c9" },
]

# : ]]]
