# : Manager [[[

[mgr]
cwd = { fg = "#e4e2e4" }

# Tab
tab_active = { fg = "#20314c", bg = "#b6c7e9", bold = true }
tab_inactive = { fg = "#d6e3ff", bg = "#081c36" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#fc73ea", bg = "#fc73ea" }
marker_cut = { fg = "#fed7f9", bg = "#fed7f9" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#e0bbdc", bg = "#e0bbdc" }

# Count
count_copied = { fg = "#2a132b", bg = "#fed7f9" }
count_cut = { fg = "#2a132b", bg = "#fed7f9" }
count_selected = { fg = "#20314c", bg = "#e0bbdc" }

# Border
border_symbol = "│"
border_style  = { fg = "#b6c7e9" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#20314c", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#b6c7e9", fg = "#20314c", bold = true }
normal_alt  = { bg = "#44474d", fg = "#c5c6ce" }

# Select mode
select_main = { bg = "#c1c6d5", fg = "#2a313c", bold = true }
select_alt  = { bg = "#44474d", fg = "#c5c6ce" }

# Unset mode
unset_main = { bg = "#e0bbdc", fg = "#412741", bold = true }
unset_alt  = { bg = "#44474d", fg = "#c5c6ce" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#b6c7e9", bg = "#39393b" }
progress_error = { fg = "#ffb4ab", bg = "#39393b" }

# Permissions
permissions_t = { fg = "#667297" }
permissions_w = { fg = "#b052a6" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#fa42e3" }
permissions_s = { fg = "#3d7bff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#b6c7e9" }
active = { fg = "#e0bbdc", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#b6c7e9" }
value = { fg = "#e4e2e4" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#b6c7e9", bg = "#20314c" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#b6c7e9" }
title = {}
hovered = { fg = "#fed7f9", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#39393b" }
cand = { fg = "#b6c7e9" }
rest = { fg = "#20314c" }
desc = { fg = "#e4e2e4" }
separator = " ▶ "
separator_style = { fg = "#e4e2e4" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e4e2e4" }
run = { fg = "#e4e2e4" }
footer = { fg = "#2a313c", bg = "#c1c6d5" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#e0bbdc" }
title_warn = { fg = "#b6c7e9" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e4e2e4" },
    { name = "*/", fg = "#b6c7e9" },
]

# : ]]]
