# : Manager [[[

[mgr]
cwd = { fg = "#f0dfd7" }

# Tab
tab_active = { fg = "#512300", bg = "#ffb689", bold = true }
tab_inactive = { fg = "#ffdbc8", bg = "#311300" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#d0cc5d", bg = "#d0cc5d" }
marker_cut = { fg = "#e7e5ac", bg = "#e7e5ac" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#cbc992", bg = "#cbc992" }

# Count
count_copied = { fg = "#1d1d00", bg = "#e7e5ac" }
count_cut = { fg = "#1d1d00", bg = "#e7e5ac" }
count_selected = { fg = "#512300", bg = "#cbc992" }

# Border
border_symbol = "│"
border_style  = { fg = "#ffb689" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#512300", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#ffb689", fg = "#512300", bold = true }
normal_alt  = { bg = "#52443c", fg = "#d7c2b8" }

# Select mode
select_main = { bg = "#e5bfa9", fg = "#432b1c", bold = true }
select_alt  = { bg = "#52443c", fg = "#d7c2b8" }

# Unset mode
unset_main = { bg = "#cbc992", fg = "#323209", bold = true }
unset_alt  = { bg = "#52443c", fg = "#d7c2b8" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#ffb689", bg = "#413731" }
progress_error = { fg = "#ffb4ab", bg = "#413731" }

# Permissions
permissions_t = { fg = "#bc6939" }
permissions_w = { fg = "#85823f" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#c2bd38" }
permissions_s = { fg = "#ff772f" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#ffb689" }
active = { fg = "#cbc992", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#ffb689" }
value = { fg = "#f0dfd7" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#ffb689", bg = "#512300" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#ffb689" }
title = {}
hovered = { fg = "#e7e5ac", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#413731" }
cand = { fg = "#ffb689" }
rest = { fg = "#512300" }
desc = { fg = "#f0dfd7" }
separator = " ▶ "
separator_style = { fg = "#f0dfd7" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#f0dfd7" }
run = { fg = "#f0dfd7" }
footer = { fg = "#432b1c", bg = "#e5bfa9" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#cbc992" }
title_warn = { fg = "#ffb689" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#f0dfd7" },
    { name = "*/", fg = "#ffb689" },
]

# : ]]]
