# : Manager [[[

[mgr]
cwd = { fg = "#e1e4d7" }

# Tab
tab_active = { fg = "#1e3700", bg = "#a0d662", bold = true }
tab_inactive = { fg = "#bbf37b", bg = "#0f2000" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#05fa99", bg = "#05fa99" }
marker_cut = { fg = "#69fcc2", bg = "#69fcc2" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#46dfa7", bg = "#46dfa7" }

# Count
count_copied = { fg = "#002115", bg = "#69fcc2" }
count_cut = { fg = "#002115", bg = "#69fcc2" }
count_selected = { fg = "#1e3700", bg = "#46dfa7" }

# Border
border_symbol = "│"
border_style  = { fg = "#a0d662" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#1e3700", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#a0d662", fg = "#1e3700", bold = true }
normal_alt  = { bg = "#434939", fg = "#c3c9b5" }

# Select mode
select_main = { bg = "#b6cf98", fg = "#23360e", bold = true }
select_alt  = { bg = "#434939", fg = "#c3c9b5" }

# Unset mode
unset_main = { bg = "#46dfa7", fg = "#003826", bold = true }
unset_alt  = { bg = "#434939", fg = "#c3c9b5" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#a0d662", bg = "#373a31" }
progress_error = { fg = "#ffb4ab", bg = "#373a31" }

# Permissions
permissions_t = { fg = "#6a8d41" }
permissions_w = { fg = "#157753" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#04c87b" }
permissions_s = { fg = "#70c312" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#a0d662" }
active = { fg = "#46dfa7", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#a0d662" }
value = { fg = "#e1e4d7" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#a0d662", bg = "#1e3700" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#a0d662" }
title = {}
hovered = { fg = "#69fcc2", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#373a31" }
cand = { fg = "#a0d662" }
rest = { fg = "#1e3700" }
desc = { fg = "#e1e4d7" }
separator = " ▶ "
separator_style = { fg = "#e1e4d7" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e1e4d7" }
run = { fg = "#e1e4d7" }
footer = { fg = "#23360e", bg = "#b6cf98" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#46dfa7" }
title_warn = { fg = "#a0d662" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e1e4d7" },
    { name = "*/", fg = "#a0d662" },
]

# : ]]]
