# : Manager [[[

[mgr]
cwd = { fg = "#e5e1ea" }

# Tab
tab_active = { fg = "#2f1c7f", bg = "#c8bfff", bold = true }
tab_inactive = { fg = "#e5deff", bg = "#1a0063" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ff72be", bg = "#ff72be" }
marker_cut = { fg = "#ffd8ed", bg = "#ffd8ed" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#ffade0", bg = "#ffade0" }

# Count
count_copied = { fg = "#3b002e", bg = "#ffd8ed" }
count_cut = { fg = "#3b002e", bg = "#ffd8ed" }
count_selected = { fg = "#2f1c7f", bg = "#ffade0" }

# Border
border_symbol = "│"
border_style  = { fg = "#c8bfff" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#2f1c7f", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#c8bfff", fg = "#2f1c7f", bold = true }
normal_alt  = { bg = "#484552", fg = "#c9c4d4" }

# Select mode
select_main = { bg = "#c9c1ee", fg = "#312c50", bold = true }
select_alt  = { bg = "#484552", fg = "#c9c4d4" }

# Unset mode
unset_main = { bg = "#ffade0", fg = "#5c094a", bold = true }
unset_alt  = { bg = "#484552", fg = "#c9c4d4" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#c8bfff", bg = "#3a383f" }
progress_error = { fg = "#ffb4ab", bg = "#3a383f" }

# Permissions
permissions_t = { fg = "#6049cd" }
permissions_w = { fg = "#ff14a6" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#ff3fa6" }
permissions_s = { fg = "#6c45ff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#c8bfff" }
active = { fg = "#ffade0", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#c8bfff" }
value = { fg = "#e5e1ea" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#c8bfff", bg = "#2f1c7f" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#c8bfff" }
title = {}
hovered = { fg = "#ffd8ed", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#3a383f" }
cand = { fg = "#c8bfff" }
rest = { fg = "#2f1c7f" }
desc = { fg = "#e5e1ea" }
separator = " ▶ "
separator_style = { fg = "#e5e1ea" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e5e1ea" }
run = { fg = "#e5e1ea" }
footer = { fg = "#312c50", bg = "#c9c1ee" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#ffade0" }
title_warn = { fg = "#c8bfff" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e5e1ea" },
    { name = "*/", fg = "#c8bfff" },
]

# : ]]]
