# : Manager [[[

[mgr]
cwd = { fg = "#f0dfd7" }

# Tab
tab_active = { fg = "#502400", bg = "#ffb787", bold = true }
tab_inactive = { fg = "#ffdcc7", bg = "#311300" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ced522", bg = "#ced522" }
marker_cut = { fg = "#e4e974", bg = "#e4e974" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#c8cd5c", bg = "#c8cd5c" }

# Count
count_copied = { fg = "#1c1d00", bg = "#e4e974" }
count_cut = { fg = "#1c1d00", bg = "#e4e974" }
count_selected = { fg = "#502400", bg = "#c8cd5c" }

# Border
border_symbol = "│"
border_style  = { fg = "#ffb787" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#502400", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#ffb787", fg = "#502400", bold = true }
normal_alt  = { bg = "#544339", fg = "#dac2b4" }

# Select mode
select_main = { bg = "#f2bb99", fg = "#492810", bold = true }
select_alt  = { bg = "#544339", fg = "#dac2b4" }

# Unset mode
unset_main = { bg = "#c8cd5c", fg = "#303300", bold = true }
unset_alt  = { bg = "#544339", fg = "#dac2b4" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#ffb787", bg = "#413731" }
progress_error = { fg = "#ffb4ab", bg = "#413731" }

# Permissions
permissions_t = { fg = "#d7631b" }
permissions_w = { fg = "#6b6e22" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#a3a91b" }
permissions_s = { fg = "#ff7c2e" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#ffb787" }
active = { fg = "#c8cd5c", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#ffb787" }
value = { fg = "#f0dfd7" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#ffb787", bg = "#502400" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#ffb787" }
title = {}
hovered = { fg = "#e4e974", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#413731" }
cand = { fg = "#ffb787" }
rest = { fg = "#502400" }
desc = { fg = "#f0dfd7" }
separator = " ▶ "
separator_style = { fg = "#f0dfd7" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#f0dfd7" }
run = { fg = "#f0dfd7" }
footer = { fg = "#492810", bg = "#f2bb99" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#c8cd5c" }
title_warn = { fg = "#ffb787" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#f0dfd7" },
    { name = "*/", fg = "#ffb787" },
]

# : ]]]
