# : Manager [[[

[mgr]
cwd = { fg = "#e9e0e8" }

# Tab
tab_active = { fg = "#4b106d", bg = "#e8bdff", bold = true }
tab_inactive = { fg = "#f4d9ff", bg = "#30004b" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ff738d", bg = "#ff738d" }
marker_cut = { fg = "#ffd9e0", bg = "#ffd9e0" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#ffbaca", bg = "#ffbaca" }

# Count
count_copied = { fg = "#3f0019", bg = "#ffd9e0" }
count_cut = { fg = "#3f0019", bg = "#ffd9e0" }
count_selected = { fg = "#4b106d", bg = "#ffbaca" }

# Border
border_symbol = "│"
border_style  = { fg = "#e5b5ff" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#4b106d", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#e8bdff", fg = "#4b106d", bold = true }
normal_alt  = { bg = "#4c4450", fg = "#cfc2d1" }

# Select mode
select_main = { bg = "#dabce7", fg = "#3d284a", bold = true }
select_alt  = { bg = "#4c4450", fg = "#cfc2d1" }

# Unset mode
unset_main = { bg = "#ffbaca", fg = "#5f0f2e", bold = true }
unset_alt  = { bg = "#4c4450", fg = "#cfc2d1" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#e8bdff", bg = "#3d373e" }
progress_error = { fg = "#ffb4ab", bg = "#3d373e" }

# Permissions
permissions_t = { fg = "#9c4bbf" }
permissions_w = { fg = "#ff2154" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#ff4063" }
permissions_s = { fg = "#c840ff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#e8bdff" }
active = { fg = "#ffbaca", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#e8bdff" }
value = { fg = "#e9e0e8" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#e8bdff", bg = "#4b106d" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#e8bdff" }
title = {}
hovered = { fg = "#ffd9e0", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#3d373e" }
cand = { fg = "#e8bdff" }
rest = { fg = "#4b106d" }
desc = { fg = "#e9e0e8" }
separator = " ▶ "
separator_style = { fg = "#e9e0e8" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e9e0e8" }
run = { fg = "#e9e0e8" }
footer = { fg = "#3d284a", bg = "#dabce7" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#ffbaca" }
title_warn = { fg = "#e8bdff" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e9e0e8" },
    { name = "*/", fg = "#e5b5ff" },
]

# : ]]]
