# : Manager [[[

[mgr]
cwd = { fg = "#f6ddd6" }

# Tab
tab_active = { fg = "#5d1800", bg = "#ffb59d", bold = true }
tab_inactive = { fg = "#ffdbd0", bg = "#390b00" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ffcc08", bg = "#ffcc08" }
marker_cut = { fg = "#ffe16e", bg = "#ffe16e" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#e1c555", bg = "#e1c555" }

# Count
count_copied = { fg = "#221b00", bg = "#ffe16e" }
count_cut = { fg = "#221b00", bg = "#ffe16e" }
count_selected = { fg = "#5d1800", bg = "#e1c555" }

# Border
border_symbol = "│"
border_style  = { fg = "#ffb59d" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#5d1800", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#ffb59d", fg = "#5d1800", bold = true }
normal_alt  = { bg = "#59413a", fg = "#e0bfb5" }

# Select mode
select_main = { bg = "#ffb59d", fg = "#55200d", bold = true }
select_alt  = { bg = "#59413a", fg = "#e0bfb5" }

# Unset mode
unset_main = { bg = "#e1c555", fg = "#3a3000", bold = true }
unset_alt  = { bg = "#59413a", fg = "#e0bfb5" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#ffb59d", bg = "#453631" }
progress_error = { fg = "#ffb4ab", bg = "#453631" }

# Permissions
permissions_t = { fg = "#ff4104" }
permissions_w = { fg = "#856f18" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#d4a800" }
permissions_s = { fg = "#ff6637" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#ffb59d" }
active = { fg = "#e1c555", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#ffb59d" }
value = { fg = "#f6ddd6" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#ffb59d", bg = "#5d1800" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#ffb59d" }
title = {}
hovered = { fg = "#ffe16e", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#453631" }
cand = { fg = "#ffb59d" }
rest = { fg = "#5d1800" }
desc = { fg = "#f6ddd6" }
separator = " ▶ "
separator_style = { fg = "#f6ddd6" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#f6ddd6" }
run = { fg = "#f6ddd6" }
footer = { fg = "#55200d", bg = "#ffb59d" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#e1c555" }
title_warn = { fg = "#ffb59d" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#f6ddd6" },
    { name = "*/", fg = "#ffb59d" },
]

# : ]]]
