# : Manager [[[

[mgr]
cwd = { fg = "#ebe0dc" }

# Tab
tab_active = { fg = "#4c270c", bg = "#f9bb95", bold = true }
tab_inactive = { fg = "#ffdbc8", bg = "#321300" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#d3d053", bg = "#d3d053" }
marker_cut = { fg = "#e8e6a4", bg = "#e8e6a4" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#cecb8c", bg = "#cecb8c" }

# Count
count_copied = { fg = "#1d1d00", bg = "#e8e6a4" }
count_cut = { fg = "#1d1d00", bg = "#e8e6a4" }
count_selected = { fg = "#4c270c", bg = "#cecb8c" }

# Border
border_symbol = "│"
border_style  = { fg = "#f7b994" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#4c270c", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#f9bb95", fg = "#4c270c", bold = true }
normal_alt  = { bg = "#51443d", fg = "#d6c3b9" }

# Select mode
select_main = { bg = "#e1c0ae", fg = "#402c1f", bold = true }
select_alt  = { bg = "#51443d", fg = "#d6c3b9" }

# Unset mode
unset_main = { bg = "#cecb8c", fg = "#333202", bold = true }
unset_alt  = { bg = "#51443d", fg = "#d6c3b9" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#f9bb95", bg = "#3e3835" }
progress_error = { fg = "#ffb4ab", bg = "#3e3835" }

# Permissions
permissions_t = { fg = "#b46a42" }
permissions_w = { fg = "#87843a" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#c2be31" }
permissions_s = { fg = "#ff772f" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#f9bb95" }
active = { fg = "#cecb8c", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#f9bb95" }
value = { fg = "#ebe0dc" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#f9bb95", bg = "#4c270c" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#f9bb95" }
title = {}
hovered = { fg = "#e8e6a4", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#3e3835" }
cand = { fg = "#f9bb95" }
rest = { fg = "#4c270c" }
desc = { fg = "#ebe0dc" }
separator = " ▶ "
separator_style = { fg = "#ebe0dc" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#ebe0dc" }
run = { fg = "#ebe0dc" }
footer = { fg = "#402c1f", bg = "#e1c0ae" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#cecb8c" }
title_warn = { fg = "#f9bb95" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#ebe0dc" },
    { name = "*/", fg = "#f7b994" },
]

# : ]]]
