source = ~/.config/hypr/colors.conf
$password_font = JetBrainsMono Nerd Font
$font = HYWenHei

background {
  monitor =
  path = ~/.current_wallpaper
  blur_passes = 3
  blur_size = 1
}

# Password Field
input-field {
  monitor =
  size = 20%, 5%
  outline_thickness = 1

  inner_color = rgba($baseAlphaBF)
  outer_color = $mauve
  check_color = $yellow
  fail_color  = $red

  font_color = $overlay0
  font_family = $password_font
  fade_on_empty = false
  rounding = 25

  position = 0, 50
  halign = center
  valign = bottom
}

# Hour
label {
  monitor =
  text = cmd[update:1000] date +%H
  text_align = center

  color = $text
  font_size = 120
  font_family = $font

  shadow_passes = 3
  shadow_size = 5
  shadow_color = rgba(0,0,0,0.3)

  position = 0, 100
  halign = center
  valign = center
}

# Minute
label {
  monitor =
  text = cmd[update:1000] date +%M
  text_align = center

  color = $text
  font_size = 120
  font_family = $font

  shadow_passes = 3
  shadow_size = 5
  shadow_color = rgba(0,0,0,0.1)

  position = 0, -65
  halign = center
  valign = center
}

# Date
label {
  monitor =
  text = cmd[update:1000] date +'%A, %d %B, %Y'
  text_align = center

  color = $subtext1
  font_size = 16
  font_family = $font

  shadow_passes = 3
  shadow_size = 5
  shadow_color = rgba(0,0,0,0.1)

  position = 0, -160
  halign = center
  valign = center
}

# Greeter
# label {
#   monitor =
#   text = Hello, $USER
#   text_align = center
#
#   color = $subtext1
#   font_size = 20
#   font_family = $font
#
#   shadow_passes = 3
#   shadow_size = 5
#   shadow_color = rgba(0,0,0,0.1)
#
#   position = 0, 205
#   halign = center
#   valign = center
# }

# Layout
label {
  monitor =
  text =   $LAYOUT
  text_align = left

  color = $overlay0
  font_size = 12
  font_family = $font

  position = 15, 15
  halign = left
  valign = bottom
}
